import "@styles/globals.css";
import NotificationProvider from "@utils/notificationcontext";
import DisableCopying from "@utils/disablecopying";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="cs">
			<body>
				<NotificationProvider>
					{children}
				</NotificationProvider>
			</body>
		</html>
	);
}
